"""spell_check

Revision ID: 444fe7f8c126
Revises: 64fc3bdf8bfe
Create Date: 2026-01-26 22:39:44.597578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444fe7f8c126'
down_revision: Union[str, Sequence[str], None] = '64fc3bdf8bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(), nullable=False))
        batch_op.drop_column('naionality')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('naionality', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
