"""nationality

Revision ID: fad63532e907
Revises: c42d3b0ef150
Create Date: 2026-01-26 16:09:17.233005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad63532e907'
down_revision: Union[str, Sequence[str], None] = 'c42d3b0ef150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('naionality', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.drop_column('naionality')

    # ### end Alembic commands ###
